config/routes.rb
Rails.application.routes.draw do
  root to: 'gossips#index'
  resources :gossips
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
  	@gossips = Gossip.all
  end

  def new
  	@gossip = Gossip.new
  end

  def create
  	@gossip = Gossip.new(gossip_params)
  	if @gossip.save
  	  redirect_to gossip_path(@gossip)
  	else
  	  render 'new'
  	end
  end

  def show
  	@gossip = Gossip.find(params[:id])
  end

  def edit
  	@gossip = Gossip.find(params[:id])
  end

  def update
  	@gossip = Gossip.find(params[:id])
  	new_gossip = gossip_params
  	if @gossip.update(new_gossip)
  	  redirect_to gossip_path(@gossip)
  	else
  	  render 'edit'
  	end
  end

  def destroy
  	@gossip = Gossip.find(params[:id])
  	@gossip.destroy
  	redirect_to gossips_path
  end

  private
  def gossip_params
  	params.require(:gossip).permit(:anonymous_author, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<h1>Edition du gossip</h1>

<br/>

<%= form_for @gossip do |f| %>
  	<div class='form-group'>
		<label>Pseudo</label>
		<%= f.text_field :anonymous_author, class: 'form-control' %>
	</div>
	<div class='form-group'>
		<label>Contenu du gossip</label>
		<%= f.text_field :content, class: 'form-control' %>
	</div>
	<br/>
	<div class='form-group'>
		<button type='submit' class='btn btn-success'>Editer le gossip</button>
		<a href='<%= gossip_path(@gossip.id) %>' class='btn btn-danger' data-confirm='Etes vous sur?' data-method='DELETE'>Supprimer</a>
		<a href='<%= gossips_path %>' class='btn btn-primary'>Revenir à la liste des gossips</a>
	</div>
<% end %>

app/views/gossips/index.html.erb
<h1><u>Liste des gossips</u></h1>

<br/>

<table class='table'>
	<thead>
		<tr>
			<td><strong>Auteur</strong></td>
			<td><strong>Contenu</strong></td>
			<td><strong>Actions</strong></td>
		</tr>
	</thead>
	<tbody>
		<% @gossips.each do |gossip| %>
			<tr>
				<td><%= gossip.anonymous_author %></td>
				<td><%= gossip.content %></td>
				<td>
					<a href='<%= gossip_path(gossip.id) %>' class='btn btn-primary'>En savoir plus</a>
					<a href='<%= edit_gossip_path(gossip.id) %>'class='btn btn-warning'>Editer</a>
					<a href='<%= gossip_path(gossip.id) %>' class='btn btn-danger' data-confirm='Etes vous sur?' data-method='DELETE'>Supprimer</a>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<br/>

<p>
	<a href='<%= new_gossip_path %>' class='btn btn-success'>Poster un nouveau gossip</a>
</p>

app/views/gossips/new.html.erb
<h1>Nouveau gossip</h1>

<br/>

<%= form_for @gossip do |f| %>
  	<div class='form-group'>
		<label>Pseudo</label>
		<%= f.text_field :anonymous_author, class: 'form-control' %>
	</div>
	<div class='form-group'>
		<label>Contenu du gossip</label>
		<%= f.text_field :content, class: 'form-control' %>
	</div>
	<div class='form-group'>
		<a type='submit' class='btn btn-success'>Poster le gossip</a>
		<a href='<%= gossips_path %>' class='btn btn-primary'>Revenir à la liste des gossips</a>
	</div>
<% end %>

app/views/gossips/show.html.erb
<h1><strong>Auteur : </strong><%= @gossip.anonymous_author %></h1>

<p><%= @gossip.content %></p>

<p>
	<a href='<%= gossips_path %>' class='btn btn-primary'>Revenir à la liste des gossips</a>
	<a href='<%= edit_gossip_path %>' class='btn btn-warning'>Editer</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>